### ISSUE TITLE
A question about test.py

### ISSUE THREAD

**Issue by tanggirltt** [xmengli999/H-DenseUNet#33]
Hello,when I run test.py,there is a question
_Traceback (most recent call last):
  File "test.py", line 124, in <module>
    predict(args)
  File "test.py", line 111, in predict
    Segmask = np.dot(Segmask,liver_labels)
ValueError: shapes (512,512,75) and (512,512,163) not aligned: 75 (dim 2) != 512 (dim 1)_
I have change  Segmask = Segmask*liver_labels as  Segmask = np.dot(Segmask,liver_labels)
Anyone could explain this question?thanks!

**Comment by xmengli999** [comment]
The liver mask you load is the one in the "test data", however, I think you load the "train data" for testing?

**Comment by wangn123** [comment]
hello，I met the same problem. Have you solved it? Can you tell me the solution. thanks a lot
