### ISSUE TITLE
Problem run test.py

### ISSUE THREAD

**Issue by agatakrason** [xmengli999/H-DenseUNet#48]
Hello,

Thanks really nice paper. I am so impressed about work that you have already done. 
I would like to run your code. 
I am getting an error running test.py
Could you help me please ?

```
C:\Users\krasona\PycharmProjects\HCCLiver\venv\Scripts\python.exe C:/Users/krasona/PycharmProjects/HCCLiver/test.py
Using TensorFlow backend.
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\krasona\PycharmProjects\HCCLiver\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "C:/Users/krasona/PycharmProjects/HCCLiver/test.py", line 4, in <module>
    from keras import backend as K
  File "Keras-2.0.8\keras\__init__.py", line 4, in <module>
    from . import activations
  File "Keras-2.0.8\keras\activations.py", line 6, in <module>
    from .engine import Layer
  File "Keras-2.0.8\keras\engine\__init__.py", line 3, in <module>
    from .topology import InputSpec
  File "Keras-2.0.8\keras\engine\topology.py", line 8, in <module>
    import yaml
  File "Keras-2.0.8\yaml\__init__.py", line 2, in <module>
    from error import *
ModuleNotFoundError: No module named 'error'
```

**Comment by sherridxy** [comment]
Hi, can you solve that above all problems? and I can not understand this problem ,envionment...

**Comment by agatakrason** [comment]
What are exactly settings that you run  your software ?
I mean versions of libraries and python ?



wt., 1 paź 2019 o 13:58 sherridxy <notifications@github.com> napisał(a):
