### ISSUE TITLE
No module named 'custom_layers'

### ISSUE THREAD

**Issue by mubeenmeo344** [xmengli999/H-DenseUNet#54]
/media/brl/94AEC7B1AEC78A66/Diagnosis1/venv/bin/python /media/brl/94AEC7B1AEC78A66/Diagnosis1/train_2ddense.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/media/brl/94AEC7B1AEC78A66/Diagnosis1/train_2ddense.py", line 16, in <module>
    from denseunet import DenseUNet
  File "/media/brl/94AEC7B1AEC78A66/Diagnosis1/denseunet.py", line 25, in <module>
    from custom_layers import Scale
ImportError: No module named custom_layers

Process finished with exit code 1
kindly tell me that where this file is located?
Is this is a built-in file in keras??

Thanks in Advance.

**Comment by wangn123** [comment]
Has the problem been solved? I had the same problem，If it is solved, can you let me know? thanks a lot

**Comment by Liuyixuan95** [comment]
I have the same problem,too

**Comment by Liuyixuan95** [comment]
I solved it.  
modify the line 4 and 5 in denseunet.py to ./Keras-2.0.8
