### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (512,512,155) (512,512,55)

### ISSUE THREAD

**Issue by vijaygcr1** [xmengli999/H-DenseUNet#58]
I tried to follow the procedure and execute the codes and to some extent I executed. But few places I got stuck such as while running test.py it gives shape error in 
Segmask = Segmask * liver_labels 
as

------------------------------
Traceback (most recent call last):
  File "/media/New Volume/RnD/Liver/H-DenseUNet-master/test.py", line 146, in <module>
    predict(args)
![error hdenseunet](https://user-images.githubusercontent.com/42180306/68525004-479cfa80-02f3-11ea-9b3d-a63e0ae19086.png)

  File "/media/New Volume/RnD/Liver/H-DenseUNet-master/test.py", line 133, in predict
    Segmask = Segmask * liver_labels
ValueError: operands could not be broadcast together with shapes (512,512,155) (512,512,55)

**Comment by xmengli999** [comment]
The model is trained for the test dataset. Maybe you load the training data for testing
